name: ilimgroup_jobs
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-56.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.2
  routemaster: ^0.9.5
  auto_size_text: ^3.0.0
  retrofit: ^3.0.1+1
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  json_annotation: ^4.4.0
  jwt_decode: ^0.3.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  file_picker: ^4.5.1
  #zefyrka: ^1.1.1
  zefyr: 1.0.0-rc.5
  intl: ^0.17.0
  blur: ^3.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700