name: Dart

on:
  push:
    branches: [ static ]
  pull_request:
    branches: [ static ]
jobs:         
  publish:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
       ref: 'static'
    - id: deploy
      name: Deploy to dokku
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
       git-push-flags: '--force'
       ssh-private-key: ${{ secrets.DEPLOY_KEY }}
       dokku-host: '51.250.38.241'
       app-name: 'ilimjob'
