name: flutter deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**
  pull_request:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**

env:
  JAVA_VERSION: "12.x" #change this version if you want
  FLUTTER_VERSION: "2.10.2" #set here your version
  FLUTTER_CHANNEL: "stable" #set here your channel

jobs:         
  publish:
    name: Build
    runs-on: ubuntu-latest #change it to another OS if you want
    steps:
      - name: BUILD
        working-directory: ./ilimgroup_jobs
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
      - run: |
          flutter pub get
          flutter build web --release
          cd build/web
          touch .static
          
