name: flutter deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**
  pull_request:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**

jobs:         
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
        channel: 'stable' # or: 'beta' or 'master'
     - run: | 
        flutter pub get
        flutter build web
        touch ./build/web/static
        cd ./build/web
        ls
     - working-directory: ./ilimgroup_jobs
       
     - uses: idoberko2/dokku-deploy-github-action@v1
       with:
         git-push-flags: '--force'
         ssh-private-key: ${{ secrets.DEPLOY_KEY }}
         dokku-host: '51.250.38.241'
         app-name: 'ilimjob'
     - working-directory: ./ilimgroup_jobs/build/web
     
     
          
