name: flutter deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**
  pull_request:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**

jobs:         
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'
          channel: 'stable'
      - run: |
          flutter pub get
          flutter build web --release
          cd build/web
          touch .static
          
