name: FLUTTER BUILD

on: #trigger on push & PR to this branch only
  push:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**
  pull_request:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**

jobs:         
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
     run: 
      working-directory: ./ilimgroup_jobs
    steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
        channel: 'stable' # or: 'beta' or 'master'
     - run: | 
        flutter pub get
        flutter build web
        touch ./build/web/.static
        cd ./build/web   
        
     - name: Push to static branch
       run: |
        mkdir ./build/web/.github
        mkdir ./build/web/.github/workflows
        cp ../.github/workflows/deploy.yml ./build/web/.github/workflows/deploy.yml
        cd build/web
        git init
        git config --global user.email maxnemoy@gmail.com
        git config --global user.name maxnemoy
        git status
        git remote add origin https://${{secrets.GH_KEY}}@github.com/maxnemoy/ilim_jobs.git
        git checkout -b static
        git add --all
        git commit -m "publish"
        git push origin static -f
        
       
     
          
