name: flutter deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**
  pull_request:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**

jobs:         
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: BUILD
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'
          channel: 'stable'
      - run: |
          flutter pub get
          flutter build web --release
          cd build/web
          touch .static
          
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: swith folder
      run: cd ./build/web
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - id: deploy
      name: Deploy to dokku
      
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        git-push-flags: '--force'
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        dokku-host: '188.34.194.103'
        app-name: 'medhelp'
          
