name: flutter deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**
  pull_request:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**

jobs:         
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
        channel: 'stable' # or: 'beta' or 'master'
     - run: | 
        cd ./ilimgroup_jobs
        flutter pub get
        flutter build web
        touch ./build/web/static
        cd ./build/web
        ls
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - id: deploy
    - name: Deploy to dokku
      working-directory: ./ilimgroup_jobs/build/web
    - uses: idoberko2/dokku-deploy-github-action@v1
      with:
        git-push-flags: '--force'
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        dokku-host: '51.250.38.241'
        app-name: 'ilimjob'
     
     
          
