name: flutter deploy

on: #trigger on push & PR to this branch only
  push:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**
  pull_request:
    branches:
      - master
    paths:
      - ilimgroup_jobs/**

jobs:         
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - name: build
       working-directory: ./ilimgroup_jobs
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
        channel: 'stable' # or: 'beta' or 'master'
     - run: flutter pub get
     - run: flutter build web
     - run: touch ./build/web/.static
     - run: cd ./build/web
     - run: ls
     
     
          
