name: Go Deploy

on:
  push:
    branches:
      - master
    paths:
      - server/**
  pull_request:
    branches:
      - master
    paths:
      - server/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
     run: 
      working-directory: ./server
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
          
    - name: Push to static branch
      run: |
        cp ../.github/workflows/go_deploy.yml ./build/web/.github/workflows/go_deploy.yml
        git init
        git config --global user.email maxnemoy@gmail.com
        git config --global user.name maxnemoy
        git status
        git remote add origin https://${{secrets.GH_KEY}}@github.com/maxnemoy/ilim_jobs.git
        git checkout -b server
        git add --all
        git commit -m "publish"
        git push origin server -f
       
       
 
      
